-- SISTEMA DE RECRUTAMENTO

CREATE DATABASE RECRUTAMENTO_ALAMO;

USE RECRUTAMENTO_ALAMO;

CREATE TABLE CANDIDATO(
		IDCANDIDATO INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30) NOT NULL,
		CPF VARCHAR (20) NOT NULL UNIQUE,
		ID_ENDERECO INT,
		ID_EXPERIENCIA INT,
		ID_CURRICULO INT,
		ID_EMAIL INT,
		ID_TELEFONE INT
);


CREATE TABLE CURRICULO(
		IDCURRICULO INT PRIMARY KEY AUTO_INCREMENT,
		ARQUIVO VARCHAR(30) NOT NULL UNIQUE,
		ID_CANDIDATO INT
);

CREATE TABLE ENDERECO(
		IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
		CEP VARCHAR(10) NOT NULL,
		ESTADO CHAR(2) NOT NULL,
		CIDADE VARCHAR(50) NOT NULL,
		BAIRRO VARCHAR(50) NOT NULL,
		RUA VARCHAR(50) NOT NULL,
		ID_CANDIDATO INT
);


CREATE TABLE EXPERIENCIA(
		IDEXPERIENCIA INT PRIMARY KEY AUTO_INCREMENT,
		AUTOMOTIVO ENUM('SIM','NAO') NOT NULL,
		VENDAS ENUM('SIM','NAO') NOT NULL,
		ID_CANDIDATO INT
);

CREATE TABLE TELEFONE(
		IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
		TIPO ENUM('COM','RES','CEL') NOT NULL,
		NUMERO VARCHAR(30) NOT NULL UNIQUE,
		ID_CANDIDATO INT

);

CREATE TABLE EMAIL(
		IDEMAIL INT PRIMARY KEY AUTO_INCREMENT,
		ENDERECO_EMAIL VARCHAR(255) NOT NULL UNIQUE,
		ID_CANDIDATO INT
);

ALTER TABLE CANDIDATO
ADD CONSTRAINT FK_ENDERECO_CANDIDATO 
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(IDENDERECO);

ALTER TABLE CANDIDATO
ADD CONSTRAINT FK_EXPERIENCIA_CANDIDATO 
FOREIGN KEY(ID_EXPERIENCIA) REFERENCES EXPERIENCIA(IDEXPERIENCIA);

ALTER TABLE CANDIDATO
ADD CONSTRAINT FK_CURRICULO_CANDIDATO 
FOREIGN KEY(ID_CURRICULO) REFERENCES CURRICULO(IDCURRICULO);

ALTER TABLE CANDIDATO
ADD CONSTRAINT FK_EMAIL_CANDIDATO 
FOREIGN KEY(ID_EMAIL) REFERENCES EMAIL(IDEMAIL);

ALTER TABLE CANDIDATO
ADD CONSTRAINT FK_TELEFONE_CANDIDATO 
FOREIGN KEY(ID_TELEFONE) REFERENCES TELEFONE(IDTELEFONE);

ALTER TABLE CURRICULO
ADD CONSTRAINT FK_CANDIDATO_CURRICULO 
FOREIGN KEY(ID_CANDIDATO) REFERENCES CANDIDATO(IDCANDIDATO);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_CANDIDATO_ENDERECO 
FOREIGN KEY(ID_CANDIDATO) REFERENCES CANDIDATO(IDCANDIDATO);

ALTER TABLE EXPERIENCIA
ADD CONSTRAINT FK_CANDIDATO_EXPERIENCIA
FOREIGN KEY(ID_CANDIDATO) REFERENCES CANDIDATO(IDCANDIDATO);

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_CANDIDATO_TELEFONE
FOREIGN KEY(ID_CANDIDATO) REFERENCES CANDIDATO(IDCANDIDATO);

ALTER TABLE EMAIL
ADD CONSTRAINT FK_CANDIDATO_EMAIL
FOREIGN KEY(ID_CANDIDATO) REFERENCES CANDIDATO(IDCANDIDATO);


INSERT INTO CURRICULO VALUES(NULL,'PDF',NULL);
INSERT INTO ENDERECO VALUES(NULL,'21645-360','RJ','RIO DE JANEIRO','ANCHIETA','LUIS VIDAL - 210', NULL);
INSERT INTO EXPERIENCIA VALUES(NULL,'SIM','SIM',NULL);
INSERT INTO TELEFONE VALUES(NULL,'CEL','+55 (21) 97114-4067',NULL);
INSERT INTO EMAIL VALUES(NULL,'alexanderferreira106@gmail.com',NULL);
INSERT INTO CANDIDATO VALUES(NULL, 'ALEXANDER', '154.786.817-17',1,1,1,1,1);

SELECT NOME,CPF,ARQUIVO
FROM CANDIDATO
INNER JOIN CURRICULO
ON IDCURRICULO = ID_CURRICULO;

SELECT NOME,CPF,NUMERO
FROM CANDIDATO
INNER JOIN TELEFONE
ON IDTELEFONE = ID_TELEFONE;




-- ESTADO,CIDADE,BAIRRO,RUA,AUTOMOTIVO,VENDAS,NUMERO,ENDERECO_EMAIL